apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: acrterratsmarch.azurecr.io/java:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: springboot-svc
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
